CATEGORY_MAP = {
    # ... all your other sections ...

    "11) Exposure Indexing for Low Light (Cine EI)": [
        "To use Exposure Indexing in extreme low-light situations to bring out more image detail in shadow areas:",
        "1. First, it can help to use an external monitor.",
        "2. Press and release the Menu button to access the quick menu on the LCD touch screen.",
        "3. Use the multi-dial to scroll to Monitoring (page 5/10)",
        "4. Set the VF to SG3C/Slog3. This will route the SLog signal to the LCD screen.",
        "5. Set the HDMI/SDI to MLUT. This will put a LUT on your external monitor.",
        "6. Set the Base Look / LUT to s709. This is the LUT for standard viewing (as set in the previous step, the s709 LUT will only appear on your external monitor).",
        "7. Exit the LCD touch screen menu and then press and hold the Menu button to enter the camera’s full menu.",
        "    a. Scroll to Shooting > LUT On/Off",
        "    b. You will see your settings from the touch screen menu reflected here.",
        "    c. Make sure Internal Rec is set to MLUT Off (this ensures that you are only viewing the s709 LUT and not recording it 'baked in' to your footage on the media card where it can’t be undone).",
        "8. Exit the menu. Your LCD screen should now be in SLog and your external monitor should be in s709.",
        "    a. Press the Assign button on the side of the LCD screen to activate the Waveform Monitor on the LCD screen. When using an external monitor, the waveform monitor will display the signal being sent to the external monitor (either s709 or SLog) and not the LCD screen on the camera. In this case, we have assigned the s709 LUT to the external monitor, so you should see 'LUT s709' immediately above the waveform monitor on the LCD screen.",
        "9. Setting exposure indexing for extreme low-light conditions:",
        "    a. Press and hold the Menu button to access the full menu.",
        "    b. Scroll to Shooting > ISO/Gain/EI >",
        "        ii. Set Exposure Index<H> to 800EI / 6.0E",
        "        iii. Set Exposure Index<M> to 400EI / 5.0E",
        "        iv. Set Exposure Index<L> to 200EI / 4.0E",
        "It is important to note at this point that when we are in Cine EI mode to film in SLog but are not using exposure indexing for a specific lighting situation, we should always have the EI setting equal to the camera’s base ISO. In the majority of lighting situations, we are using base 800 ISO (indicated on the right sight of the camera’s viewfinder). This means that the EI should also be set to 800 (indicated at the bottom center of the viewfinder). This maximizes the camera’s dynamic range for the majority of our filming needs.",
        "10. Because you have already set your H, M, L Exposure Index levels in the previous step, you are now ready to use exposure indexing in low-light, shadowy conditions. In such situations, you will intentionally but creatively overexpose by 1 or 2 stops, depending on how dark the shadow areas are in the scene.",
        "Remember, 1 stop brighter means the camera is seeing twice as much light; 2 stops brighter means the camera is seeing 4 times as much light (each stop increase is double the amount of light from the previous stop; each stop decrease is half as much light from the previous stop).",
        "    a. To overexpose by 1 stop: Set the H, M, L toggle switch on the side of the camera to M. In the bottom middle part of the LCD screen, you should see the EI change from 800 EI to 400 EI. Notice how this change does not affect the SLog image. Exposure indexing only affects LUTs. Therefore, you should see your external monitor get darker by 1 stop of light. You’ll also see the light levels in your waveform monitor drop because they represent the s709 LUT on the external monitor.",
        "    b. Next, because we darkened the external monitor by 1 stop, we need to open up the aperture by 1 stop to compensate and to bring the brightness of the external monitor image back up to the original brightness level.",
        "        i. Open the aperture on the lens by 1 stop (for example, f/4 to f2.8)",
        "        ii. You will notice that the external monitor brightened back up by 1 stop and the SLog image on the LCD screen brightened by 1 stop. Remember, the EI setting only affects the LUT; but changing the aperture affects both the SLog and the LUT.",
        "        iii. Now, the recorded SLog footage will be 1 stop brighter, bringing out more detail in the shadow areas. Remember, we are still in Base ISO 800. EI is not the same as ISO, even though it uses the same number system. We have simply overexposed by 1 stop in Base ISO 800 in order to bring out more detai
